### ISSUE TITLE
Enhance mobile responsiveness of the trading dashboard

### ISSUE THREAD

**Issue by lenz-0x** [lenz-0x/trading-strategy-ai-svelte#1]
Problem: The trading dashboard does not display properly on mobile devices, making it hard for users to interact with key features.

Expected Outcome: The dashboard should adapt smoothly to different mobile screen sizes, ensuring all elements are accessible and usable.

Current Issues:

The interface does not scale well on screens smaller than 768px.
Text and buttons overlap, making them difficult to use.
Charts extend off the screen, requiring horizontal scrolling.
Steps to Reproduce:

Open the dashboard on a mobile device or use the responsive design mode in a web browser.
Observe the display and interaction issues.
Proposed Solution:

Adjust CSS for better responsiveness on smaller screens.
Ensure interactive elements like buttons and forms are easy to use on mobile.
Environment:

All mobile devices
Browsers: Chrome, Safari, Firefox

**Comment by hylcore-V** [comment]
i can help u to solve  this issue
